name: "Fix PHP Code Styling"

on:
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'
permissions:
  contents: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check code style (Pint)
        run: composer test:lint
